[font]
size = 7
normal.family = "monospace"
#italic.family = "jmk Modd"

[window]
padding = { x = 30, y = 30 }
opacity = 0.9

[colors.primary]
foreground = "#fafafa"
background = "#1a1a1a"

[colors.normal]
cyan = "#14929e"
red = "#c6235a"
green = "#1a9983"
yellow = "#c17634"
blue = "#14749e"
magenta = "#8356a0"
white = "#d3d3d3"
black = "#2a3033"

[colors.bright]
cyan = "#16acba"
red = "#d8346a"
green = "#32b59f"
yellow = "#d3af2e"
blue = "#328db5"
magenta = "#aa70d1"
black = "#888888"
white = "#ffffff"
