#! /bin/sh

#
# This file contains autostart commands for BSPWM
#

# sxhkd
if [ ! $(pidof sxhkd) ]; then
	#set -U SXHKD_SHELL /usr/bin/bash
	sxhkd &
else
	pkill -USR1 -x sxhkd
fi

# composite manager
if [ ! $(pidof picom) ]; then
	picom -b --config $XDG_CONFIG_HOME/picom.conf
else
	pkill -x picom
	sleep 1
	picom -b --config $XDG_CONFIG_HOME/picom.conf
fi

# notification manager
if [ ! $(pidof dunst) ]; then
	dunst &
else
	pkill -x dunst
	sleep 1
	dunst &
fi
