#! /bin/sh

#
# This file contains autostart commands for BSPWM
#

xrdb -merge -I$HOME $HOME/.Xresources
#xsetroot -cursor_name left_ptr
#xsetroot -solid "#171719"

# sxhkd
if [ ! $(pidof sxhkd) ]; then
	#set -U SXHKD_SHELL /usr/bin/bash
	sxhkd &
else
	pkill -USR1 -x sxhkd
fi

# composite manager
if [ ! $(pidof picom) ]; then
	picom -b --config $XDG_CONFIG_HOME/picom.conf
else
	pkill -x picom
	picom -b --config $XDG_CONFIG_HOME/picom.conf
fi

# notification manager
if [ ! $(pidof dunst) ]; then
	dunst &
else
	pkill -x dunst
	dunst &
fi
