#! /bin/sh

# autostart

xrdb -merge -I$HOME $HOME/.Xresources
compton -b --config $XDG_CONFIG_HOME/compton.conf
xsetroot -cursor_name left_ptr
xsetroot -solid "#171719"
$XDG_CONFIG_HOME/lemonbar/lemonbarrc &
sxhkd &
dunst &
[ -x $HOME/.fehbg ] && $HOME/.fehbg

# settings

bspc config border_width              1
bspc config window_gap                8

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

bspc config normal_border_color       "#171719"
bspc config active_border_color       "#ffffff"
bspc config focused_border_color      "#00b5b5"

bspc config top_padding               36
bspc config left_padding              2
bspc config right_padding             2

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a MPlayer state=floating
bspc rule -a Vlc state=floating
bspc rule -a Screenkey manage=off
