#! /bin/sh

# autostart

#xrandr --output DP-1-2-2 --auto --primary --output DP-1-2-1 --auto --right-of DP-1-2-2 --output eDP-1 --off
#xrandr --output eDP-1 --auto --primary --output HDMI-1 --auto --left-of eDP-1
#xrandr --output eDP-1 --auto --primary --output HDMI-1 --off
$XDG_CONFIG_HOME/bspwm/autostart

# settings

bspc config border_width              4
bspc config window_gap                14

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

bspc config normal_border_color       "#171719"
bspc config active_border_color       "#134956"
bspc config focused_border_color      "#1fa0ba"

bspc config top_padding               30
bspc config left_padding              2
bspc config right_padding             2

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc monitor DP-1-2-2 -d I II III IV V
#bspc monitor DP-1-2-1 -d VI VII VIII IX X

#bspc monitor eDP-1 -d II IV VI VII VIII IX X
#bspc monitor HDMI-1 -d I III V


bspc rule -a MPlayer state=floating
bspc rule -a vlc state=floating
bspc rule -a Octave state=floating
bspc rule -a Display state=floating center=on
bspc rule -a vtk state=floating
bspc rule -a *:matplotlib state=floating
bspc rule -a *:gnuplot_qt state=floating
bspc rule -a Screenkey manage=off
bspc rule -a *:LibFreenect state=floating
bspc rule -a feh state=floating
bspc rule -a R_x11 state=floating
