#! /bin/sh

# autostart

$XDG_CONFIG_HOME/bspwm/autostart

# settings

bspc config border_width              1
bspc config window_gap                8

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

bspc config normal_border_color       "#171719"
bspc config active_border_color       "#ffffff"
bspc config focused_border_color      "#8aa0ca"

bspc config top_padding               36
bspc config left_padding              2
bspc config right_padding             2

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a MPlayer state=floating
bspc rule -a vlc state=floating
bspc rule -a Octave state=floating
bspc rule -a Display state=floating center=on
bspc rule -a vtk state=floating
bspc rule -a *:matplotlib state=floating
bspc rule -a *:gnuplot_qt state=floating
bspc rule -a Screenkey manage=off
bspc rule -a *:LibFreenect state=floating
bspc rule -a feh state=floating
