#! /bin/sh

BUILTIN="eDP1"
MONITORF="/sys/class/drm/card0-DP-3/status"
XMONITOR="DP1-1"


function onchange_monitor {
	$XDG_CONFIG_HOME/lemonbar/lemonbarrc &
	[ -x $HOME/.fehbg ] && $HOME/.fehbg
	xset -b
}

function external {
	MONITOR="$1"
	xrandr --output $MONITOR --auto --primary --output $BUILTIN --off
	bspc monitor -d I II III IV V VI VII VIII IX X
	onchange_monitor
}

function dual {
	MONITOR1="$1"
	MONITOR2="$2"
	xrandr \
		--output $MONITOR1 --auto --primary \
		--output $MONITOR2 --auto --right-of $MONITOR1

	if [ "$MONITOR2" != "$BUILTIN" && "$MONITOR1" != "$BUILTIN" ]
	then
		xrandr --output $BUILTIN --off
	fi

	bspc monitor $MONITOR1 -d I II III IV V
	bspc monitor $MONITOR2 -d VI VII VIII IX X
	onchange_monitor
}

function internal {
	xrandr \
		--output $BUILTIN --auto --primary \
		--output DP-1-2-1 --off \
		--output DP-1-2-2 --off \
		--output HDMI-1 --off \
		--output DP1-1 --off
	bspc monitor -d I II III IV V VI VII VIII IX X
	onchange_monitor
}

function hdmi {
	dual $BUILTIN "HDMI-1"
	onchange_monitor
}

MONITOR=0
for F in /sys/class/drm/card0-DP-*
do
	STATUS=$(cat $F/status)
	if [ $STATUS == "connected" ]
	then
		MONITOR=1
		break
	fi
done

# if the external monitor is connected
if [[ $MONITOR -eq 1 ]]
then
	external $XMONITOR
# check later for dual monitors
elif [ 1 == 0 ]
then
	echo "two monitors connected" >> $XDG_CONFIG_HOME/bspwm/bspwm.log
	echo "TODO" >> $XDG_CONFIG_HOME/bspwm/bspwm.log
# else normal mode
else
	internal
fi
