#!/usr/bin/bash
DIR=$XDG_CONFIG_HOME/lemonbar

# settings
. $DIR/settings

# functions
. $DIR/battery.sh
. $DIR/weather.sh
. $DIR/audio.sh
. $DIR/net.sh
. $DIR/system.sh

# function to print icon from icon font
function icon
{
	color=$ICON_COLOR
	if [ $# -gt 1 ]
	then
		case $2 in
			warn)
				color=$ICON_COLOR_WARN
				;;
		esac
	fi
	tmp=`echo -e "$1"`
	echo "%{F$color}%{T2}$tmp%{T-}%{F-}"
}

# to not spam weather service only update once every 10 minutes
WEATHER_UPDATE_INT=600
WEATHER_COUNT=$WEATHER_UPDATE_INT

function out
{
	while true
	do
		HOST="%{F$MAGENTA}$HOSTNAME%{F-}"
		DATETIME=$(datetime)
		BAT="$(battery $BATTERY)"
		VOL="$(volume)"
		CPU=$(cpu)
		CPU_TEMP=$(cpu_temp)
		FS=$(fs)
		RAM=$(ram)

		# network info
		LAN=$(eth $LAN_DEVICE) # default to cable ethernet
		[ -z "$LAN" ] && LAN=$(wlan $WLAN_DEVICE) # in case empty use wifi info

		# update weather
		if [ "$WEATHER_COUNT" -eq "$WEATHER_UPDATE_INT" ]; then
			WEATHER="$(weather $LAT $LON)"

			if [ $? -eq 0 ]
			then
				WEATHER_COUNT=0
			fi
		else
			WEATHER_COUNT=$(( WEATHER_COUNT + 1))
		fi

		# output info
		LEFT="$DATETIME   $WEATHER"
		RIGHT="$LAN   $VOL   $RAM   $CPU   $CPU_TEMP   $FS   $BAT"
		echo "%{l}%{O20}$LEFT%{r}$RIGHT%{O20}"
		sleep 1
	done
}

# kill any other version of the bar already running
pkill -x lemonbar

# run
argv="-p -B$BG -F$FG -g$DIMENSIONS `echo "${FONTS[@]/#/-f }"`"
out | lemonbar $argv
