#!/bin/sh

################################################################################################
# file:        update
# description: script to update AUR packages.
#              In case no arguments are given we go through all packages defined in#######
#              $XDG_CONFIG_HOME/aur/packages and try to update all of them. Else we assume
#              a the name of a single package is passed as argument which we to try to update.
################################################################################################

DIR=$XDG_CONFIG_HOME/aur

# import packages
. $DIR/packages

function clean {
	git -C "$1" clean -xdf
}

function update {
	pkg=$1
	git -C "$pkg" pull
	if [[ $? == 0 ]]; then
		(cd "$pkg" && makepkg -sric)
	fi
	clean $pkg
}

function check_updates {
	pkg=$1
	git -C "$pkg" checkout -- PKGBUILD
	git -C "$pkg" fetch 2> /dev/null
	LOCAL=$(git -C "$pkg" rev-parse @)
	BASE=$(git -C "$pkg" merge-base @ @{u})
	REMOTE=$(git -C "$pkg" rev-parse @{u})

	# do nada
	if [ $LOCAL = $REMOTE ]; then
		:
	elif [ $LOCAL = $BASE ]; then
		echo "UPDATING [ `basename $pkg` ]"
		update $pkg
	elif [ $REMOTE = $BASE ]; then
		echo "NEEDS PUSH ? [ `basename $pkg` ]"
	else
		echo "DIVERGED [ `basename $pkg` ]"
	fi
}

function install {
	pkg=$1
	url="${packages[$pkg]}"
	if [ -z "$url" ]
	then
		echo "no such package"
		return
	fi
	mkdir $pkg
	git clone $url $pkg
	(cd "$pkg" && makepkg -sric)
	clean $pkg
}

if [ $# == 0 ];
then # loop through all the packages and check for updates
	for pkg in $DIR/*
	do
		if [ -d "$pkg" ]; then
			check_updates $pkg
		fi
	done
else # update specific package
	pkg=$1
	if [ ! -d $pkg ]; then
		echo "INSTALL [ $pkg ]"
		install $pkg
	#elif [ $2 = "--force" ]; then
		#update $pkg
	else
		check_updates $pkg
	fi
fi
