#
# ~/.zshrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Colors
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# don't put duplicate lines or lines starting with space in the history.
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt histignoredups
unsetopt beep notify
bindkey -e

zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu select

autoload -Uz compinit promptinit
compinit
promptinit

# set sexy PS1
RPS1="%F{8} %~ %f%k"
PS1="%n %F{8}%m ──╼ %f"

# Load custom alias definitions.
[ -r ~/.aliases ] && . ~/.aliases

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/usr/bin/micromamba";
export MAMBA_ROOT_PREFIX="/home/ximon/dev/micromamba";
__mamba_setup="$('/usr/bin/micromamba' shell hook --shell zsh --prefix '/home/ximon/dev/micromamba' 2> /dev/null)"
if [ $? -eq 0 ]; then
	eval "$__mamba_setup"
else
	if [ -f "/home/ximon/dev/micromamba/etc/profile.d/mamba.sh" ]; then
		. "/home/ximon/dev/micromamba/etc/profile.d/mamba.sh"
	else
		export PATH="/home/ximon/dev/micromamba/bin:$PATH"
	fi
fi
unset __mamba_setup
# <<< mamba initialize <<<
